name: GitHub Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "15 0 * * *"

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate main GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          filename: profile/metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_timezone: Asia/Kolkata
          output_action: commit
          committer_branch: main
          committer_message: "chore: update GitHub metrics"

      - name: Generate GitHub achievements
        uses: lowlighter/metrics@latest
        with:
          filename: profile/achievements.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C
          output_action: commit
          committer_branch: main
          committer_message: "chore: update GitHub achievements"

      - name: Generate contribution activity
        uses: lowlighter/metrics@latest
        with:
          filename: profile/activity.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          output_action: commit
          committer_branch: main
          committer_message: "chore: update GitHub activity"